spring.application.name=MagicFridgeAI

# Configuração do H2 Database
spring.datasource.url=jdbc:h2:mem:magicfridgedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o Console do H2 (acessível em /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra as queries SQL no console (útil para debug)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
